database: sqlite3://file:test.sqlite?cache=shared&mode=rwc
public_base_url: "http://127.0.0.1:8989"
certificate:
             cert: C:\temp\epagine_params\lcpSelfSigned.crt
             private_key: C:\temp\epagine_params\lcpSelfSigned.key
storage:
         filesystem:
                      directory: C:\Users\snemegeer\Documents\GitHub\src\github.com\readium\readium-lcp-server\lcpserver\files
license:
         links:
                      hint: "http://www.epagine.fr/hint" 
                      status: "http://www.epagine.fr/licenses/{license_id}/status" 